#!/usr/bin/env ruby

###A simple Twitter Bot using Ruby####

####tweet/message me on twitter with any questions @jackdhaliwal24 or brinder.dhaliwal13@gmail.com###

#1. Line above is not a comment. leave the '#'

#2. Line below is imperative - include it at top of file
require 'Twitter'

#3. Make sure to run 'gem install ruby' in your terminal.

#4. Set your keys from your new app @dev.twitter.com below. Put them in the parenthesis.
#5. IMPORTANT: If you put this code in an online repo like bitbucket or github, make sure to hide/get rid of your keys!!


client = Twitter::REST::Client.new do |config| #Read docs @ https://github.com/sferik/twitter for setting up config options
  config.consumer_key        = ""
  config.consumer_secret     = ""
  config.access_token        = ""
  config.access_token_secret = ""
end

#Line below is Code for tweeting from bot. 
#Run this file via terminal and then refresh your twitter feed. 
#It should tweet the text in paranthesis below

#client.update("Test Tweet generated by Twitter Boot - Brinder's first twitter bot. #100daysofcode")

# code to Retweet a given hashtag. In this case, the hashtag is '#rails' (CHANGE IT N PLAY!)


def run(client) #defining run method and passing in client param
  retweetKeyword = "#rails"
  while true
    re = client.search(retweetKeyword).first.id
    client.retweet(re);
    puts "Retweet: #{re} #{Time.now}";
    sleep(30); #Every 30 secs
  end

  
end

run(client);